language: nix

matrix:
  fast_finish: true
  include:
    - env: GHCVER=ghc844
    - env: GHCVER=ghc861
    - env: GHCVER=ghc863
  allow_failures:
    - env: GHCVER=ghc844
    - env: GHCVER=ghc861

before_install:
 - nix-channel --list
 - nix-channel --update

script:
 - nix-build -A stripe-haskell --argstr compiler $GHCVER --arg check true
